 
services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9003:9000"
    container_name: auth_radius_log_consumer
    restart: always
    env_file:
      - path: ./.env